set global autochdir true

# Search when typing
set global incsearch true

# Use ripgrep for grep command
set global grepcmd 'rg --vimgrep --max-columns 200'

# Shortcut keys for cycling though errors.
map global normal <c-n> ":lint-next-error<ret>"
map global normal <c-b> ":lint-previous-error<ret>"

# Map 'ö' to <space>
map global normal ö <space>
# Map <space> to ':'
map global normal <space> :

# Jump half a page with these buttons
map global normal å gtvc
map global normal ä gbvc

# Indent with tab
map global insert <tab> '<a-;><gt>'
map global insert <backtab> '<a-;><lt>'

# Expand tabs to spaces
map global insert <tab> '<a-;><gt>'
map global insert <backtab> '<a-;><lt>'
set global tabstop 4

# Copy and paste to system clipboard
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_reg_dquote" | xsel --input --clipboard
}}
map global user P '!xsel --output --clipboard<ret>'
map global user p '<a-!>xsel --output --clipboard<ret>'

hook global BufOpenFifo '\*grep\*' %{
    map -- global normal - ':grep-next-match<ret>'
    map -- global normal _ ':grep-previous-match<ret>'
}
hook global BufOpenFifo '\*make\*' %{
    map -- global normal - ':make-next-error<ret>'
    map -- global normal _ ':make-next-error<ret>'
}

# Discern CamelCase words as separate
# def -hidden select-next-word %{
#     exec /[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
# }
# def -hidden extend-next-word %{
#     exec ?[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
# }
# def -hidden select-prev-word %{
#     exec <a-/>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
# }
# def -hidden extend-prev-word %{
#     exec <a-?>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
# }
# map global normal w :select-next-word<ret>
# map global normal W :extend-next-word<ret>
# map global normal b :select-prev-word<ret>
# map global normal B :extend-prev-word<ret>

# Make x select lines downward, and X select lines upward
def -hidden extend-line-down %{
    exec "<a-:>X"
}
def -hidden extend-line-up %{
    exec "<a-:><a-;>K<a-x>"
}


# Hooks
hook global WinCreate .* %{
    map global normal x ":extend-line-down <ret>"
    map global normal X ":extend-line-up <ret>"

    # Line numbers
    addhl number_lines -relative

    # Highlight matching parentheses
    addhl show_matching

    # Enable lint gutter
    lint-enable
}

hook global BufWritePost .* %{
    # Lint file on save
    lint
}
