# Search when typing
set global incsearch true

# Line numbers
hook global WinCreate .* %{addhl number_lines}

# Indent with tab
map global insert <tab> '<a-;><gt>'
map global insert <backtab> '<a-;><lt>'

# Expand tabs to spaces
map global insert <tab> '<a-;><gt>'
map global insert <backtab> '<a-;><lt>'
set global tabstop 4

# Copy and paste to system clipboard
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_reg_dquote" | xsel --input --clipboard
}}
map global user P '!xsel --output --clipboard<ret>'
map global user p '<a-!>xsel --output --clipboard<ret>'

